spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      platform: h2

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.user
  configuration:
    map-underscore-to-camel-case: true